version: "3"
services:
  manager:
    image: crackhash:0.1
    restart: always
    environment:
      - HASH_WORKERS=1
    ports: ["8081:8080"]
    depends_on:
      - "worker"
  worker:
    image: crackhash:0.1
    ports: ["8082:8080"]
